### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by alextartan** [CopernicaMarketingSoftware/PHP-JS#1]
Followed the steps provided at http://php-javascript.com/documentation/installation

I got: 

```
PHP Warning:  PHP Startup: Unable to load dynamic library 
'/usr/lib/php5/20131226/php-js.so' - /usr/lib/php5/20131226/php-js.so: 
undefined symbol:   
_ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_6HandleIS4_EENSA_INS_9SignatureEEEi 
in Unknown on line 0`
```

**Comment by BartCopernica** [comment]
The solution for now is compiling v8 4.4.9.1 with two changes mentioned in the comments on the bottom of the documentation page. After that PHP-JS can be compiled properly. We'll have a look at a nicer solution later on.

**Comment by alextartan** [comment]
After your latest updates, I ran everything again (clean setup)

Now i get:

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/php-js.so' - /usr/lib/php5/20131226/php-js.so: undefined symbol: _ZNK2v88TryCatch13HasTerminatedEv in Unknown on line 0

The only relevant info I could find was:   
http://upstream.rosalinux.ru/compat_reports/v8/3.18.2_to_3.18.3/abi_compat_report.html
under: TryCatch::HasTerminated (needs a click to expand and show the symbol)

**Comment by ghost** [comment]
Just an update: The issue you were running into is fixed in the latest version of PHP-JS. It has been updated to use a much newer version of v8. Please let us know should you run into any further issues.
