### ISSUE TITLE
Compatibilities 

### ISSUE THREAD

**Issue by GeraudBourdin** [CopernicaMarketingSoftware/PHP-JS#10]
Hello, 

I 've just discovered this project and sound interresting as i ve used the php/v8js module. 
i can't see any config / version enabled with this module ? Is it  php 8.1 compatbile  ? 

Thanks for answer.

**Comment by EmielBruijntjes** [comment]
No, I don't think it is. It works with PHP-CPP and that is not yet ported to PHP 8
