### ISSUE TITLE
Nginx support?

### ISSUE THREAD

**Issue by smebberson** [CopernicaMarketingSoftware/PHP-JS#6]
This looks like an interesting little tool. In the installation directions the last thing is to enable an Apache mod. Does PHP-JS support being used via Nginx and PHP-FPM?

Thanks!

**Comment by ghost** [comment]
I don't really get the question. Where do you see instructions for enabling an Apache mod? It's not in our manual and not necessary. I cannot see any reason why it would not work on Nginx either.

**Comment by smebberson** [comment]
In fact, you're write. I misread that. I thought it was on this page http://www.php-js.com/documentation/installation under "Installting PHP-JS" but it just directs to enable to the PHP extension.
